### PR TITLE
Add scripts for building .rpm package.

### PR DESCRIPTION
**Pull request by larkmjc**
I've tested the rpm build script with docker locally, however, we need to test it with a tag. Also, this change will double the Travis build time (which isn't an issue if the current build is under 25 mins). 

After testing, we may want to squash this into the .deb commit so there is a single commit to cherry-pick.

### CODE REVIEW

**Comment by larkmjc** [comment]
@richardxia it looks like the build scripts ran even though there was no tag.

**Comment by richardxia** [comment]
The build scripts still run, but it won't do the actual upload unless if it's a tag build. I think it's still valuable to build on every PR, since it helps us catch errors.

In your build, it looks like it failed because the RPM filename has the string `-0.0UNTAGGED` in it twice.

**Comment by larkmjc** [comment]
Odd. It works locally.

This is shell code that splits the package version and release suffix:

```
$ PACKAGE_VERSION=3.920-0sifive1
$ pkg_version=$(echo ${PACKAGE_VERSION} | cut -d- -f1)
$ pkg_release=$(echo ${PACKAGE_VERSION} | cut -d- -f2)
$ echo $pkg_version
3.920
$ echo $pkg_release
0sifive1
```

I'll take a closer look at the log...

**Comment by larkmjc** [comment]
Oh right. It's this substitution here. There is no hyphen if TRAVIS_TAG is not set.

`docker run --rm -e PACKAGE_VERSION=${TRAVIS_TAG:-0.0UNTAGGED} -v $PWD:/usr/src/app verilator-centos ./build-rpm.sh`

**Comment by larkmjc** [comment]
I've added a hyphen and squashed back into the same commit. We'll try again...

**Comment by richardxia** [comment]
The lack of a hyphen was intentional for the .deb package, since I was following Ubuntu's package naming convention as described here: https://askubuntu.com/questions/620533/how-does-ubuntu-name-packages

I'm not an expert at Debian/Ubuntu package naming, but we should make sure whatever we do is compatible with `apt`.

**Comment by larkmjc** [comment]
This is only the untagged name in which case the package is never used so does it matter?

**Comment by larkmjc** [comment]
With this commit I've made the centos packaging depend on a hyphen to split the version and release. 

All of the present tags have hyphens.

I could harden the script a little in case it gets a tag without a hyphen, where it uses the tag for the Version and sets the Release to 0 or 1.

**Comment by richardxia** [comment]
Sorry, I forgot the exact string that I used for the real releases that I created, and I see now that they contain a hyphen between the version and the release. Apparently Debian calls the portion after the hyphen a ["revision"](https://www.debian.org/doc/debian-policy/#s-f-version).

Yes, I now think that the change you made is correct.

**Comment by larkmjc** [comment]
It seems the .deb and .rpm schemes are somewhat similar however the fields need to be explicitly split for rpm. For .deb it appears it is just a convention to separate the upstream version number and package release with a hyphen.

**Comment by larkmjc** [comment]
It appeared to make the rpm fine this time.

**Comment by larkmjc** [comment]
These two lines from `build-rpm.sh` could possibly be hardened, perhaps using regex e.g. ${PACKAGE_VERSION/foo/bar}

```
pkg_version=$(echo ${PACKAGE_VERSION} | cut -d- -f1)
pkg_release=$(echo ${PACKAGE_VERSION} | cut -d- -f2)
```

We should make a tag and check the rpm...

**Review by richardxia — APPROVED** [review]
LGTM! Feel free to recreate the existing tags to create new GitHub releases with the RPMs.

**Pull request merged**
